INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Peter', '79112345678', '4213213');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Helga', '79118765432', 'adsdasd');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Kark', '79118763132', 'qwerty');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Mister', '75893214456', 'vdmuq');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Userflow', '73326448443', 'meowlow');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Michael', '73567574432', 'aaskvmc');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Dave', '71356462388', 'sambasamba');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Megan', '75464449887', 'rumba228');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Silvester', '72233567821', 'kringecommitowner');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Grisha', '12345678912', 'mysqlslave');
INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Oleg', '79833211139', 'verystrange!');