INSERT INTO users (username, PHONE_NUMBER, password)
VALUES ('Peter', '79112345678', '4213213'),
       ('Helga', '79118765432', 'adsdasd'),
       ('Kark', '79118763132', 'qwerty'),
       ('Mister', '75893214456', 'vdmuq'),
       ('Userflow', '73326448443', 'meowlow'),
       ('Michael', '73567574432', 'aaskvmc'),
       ('Dave', '71356462388', 'sambasamba'),
       ('Megan', '75464449887', 'rumba228'),
       ('Silvester', '72233567821', 'kringecommitowner'),
       ('Grisha', '12345678912', 'mysqlslave'),
       ('Oleg', '79833211139', 'verystrange!');