INSERT INTO establishments (NAME, DESCRIPTION, ADDRESS, OWNER_ID, CATEGORY)
VALUES ('Red Rabbit', 'Small pizza-bar near to NSU', 'Novosibirsk, Ilyich St. 8', 11, 'restaurant');
INSERT INTO establishments (NAME, DESCRIPTION, ADDRESS, OWNER_ID, CATEGORY)
VALUES ('Respublica', 'Bar in the center of the Novosibirsk', 'Novosibirsk, Lenin St. 6', 11, 'restaurant');
INSERT INTO establishments (NAME, DESCRIPTION, ADDRESS, OWNER_ID, CATEGORY)
VALUES ('Marriott', '5-stars hotel', 'Novosibirsk, Ordzonikidze St. 31', 11, 'hotel');
INSERT INTO establishments (NAME, DESCRIPTION, ADDRESS, OWNER_ID, CATEGORY)
VALUES ('Marines Park Hotel', '4-stars hotel', 'Tashkent, Amir Temur Av., 79', 11, 'hotel');